# Nombre del workflow (lo verás en la pestaña "Actions" de GitHub)
name: Desplegar Backend en Azure App Service

# Triggers
on:
  # 1. Cuando se mergea a 'main'
  push:
    branches:
      - main
  # 2. Trigger MANUAL: (Solo aparecerá después del primer merge a 'main')
  workflow_dispatch:

jobs:
  build-and-deploy:
    # Usamos el sistema operativo estándar para builds
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código del repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2. Login en Azure
      - name: 'Login en Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Login en el ACR
      - name: 'Login en Azure Container Registry (ACR)'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}

      # 4. Construye y Sube la imagen Docker al ACR
      - name: Construir y subir la imagen Docker
        run: |
          docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/fitapp-backend:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/fitapp-backend:${{ github.sha }}

      # 5. Despliega en Azure App Service
      - name: 'Desplegar en Azure App Service'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fitapp-backend-api'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/fitapp-backend:${{ github.sha }}'

      # 6. Logout de Azure por seguridad
      - name: Logout de Azure
        if: always() 
        run: |
          docker logout ${{ secrets.ACR_LOGIN_SERVER }}
          az logout
